name = "deepseek-api-key"
main = "worker.js"
compatibility_date = "2024-06-01"

[[kv_namespaces]]
binding = "USERS_KV"
id = "633f61558d924751b0cc535edb74192f"

[[kv_namespaces]]
binding = "DREAMS_KV"
id = "805353c9b2d74903a7c73da3a63eef4d"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "3544f1bdc36a497a86a8d3458f86d882"

[[d1_databases]]
binding = "DB"
database_name = "saviora_dreams_database"
database_id = "7de5946b-5bb2-4da2-9956-b4a9276a090a"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "avatars-bucket"
preview_bucket_name = "avatars-bucket-preview"